

package com.skydoves.compose.stability.compiler.tests;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.skydoves.compose.stability.compiler.tests.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-tests/src/test/data/box")
@TestDataPath("$PROJECT_ROOT")
public class BoxTestGenerated extends AbstractBoxTest {
  private void run(String fileName) {
    runTest("compiler-tests/src/test/data/box/" + fileName);
  }

  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/box"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("StableDataClass.kt")
  public void testStableDataClass() {
    run("StableDataClass.kt");
  }

  @Test
  @TestMetadata("TraceAllBox.kt")
  public void testTraceAllBox() {
    run("TraceAllBox.kt");
  }

  @Test
  @TestMetadata("TraceRecomposition.kt")
  public void testTraceRecomposition() {
    run("TraceRecomposition.kt");
  }
}
