

package com.skydoves.compose.stability.compiler.tests;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.skydoves.compose.stability.compiler.tests.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-tests/src/test/data/diagnostic")
@TestDataPath("$PROJECT_ROOT")
public class DiagnosticTestGenerated extends AbstractDiagnosticTest {
  private void run(String fileName) {
    runTest("compiler-tests/src/test/data/diagnostic/" + fileName);
  }

  @Test
  public void testAllFilesPresentInDiagnostic() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/diagnostic"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("StableParameter.kt")
  public void testStableParameter() {
    run("StableParameter.kt");
  }

  @Test
  @TestMetadata("UnstableParameter.kt")
  public void testUnstableParameter() {
    run("UnstableParameter.kt");
  }
}
