

package com.skydoves.compose.stability.compiler.tests;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.skydoves.compose.stability.compiler.tests.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-tests/src/test/data/dump/ir")
@TestDataPath("$PROJECT_ROOT")
public class IrDumpTestGenerated extends AbstractIrDumpTest {
  private void run(String fileName) {
    runTest("compiler-tests/src/test/data/dump/ir/" + fileName);
  }

  @Test
  public void testAllFilesPresentInIr() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/ir"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("ComposableWithTraceRecomposition.kt")
  public void testComposableWithTraceRecomposition() {
    run("ComposableWithTraceRecomposition.kt");
  }

  @Test
  @TestMetadata("MutableDataClass.kt")
  public void testMutableDataClass() {
    run("MutableDataClass.kt");
  }

  @Test
  @TestMetadata("SimpleDataClass.kt")
  public void testSimpleDataClass() {
    run("SimpleDataClass.kt");
  }

  @Test
  @TestMetadata("TraceAllInjection.kt")
  public void testTraceAllInjection() {
    run("TraceAllInjection.kt");
  }

  @Test
  @TestMetadata("TraceRecompositionInjection.kt")
  public void testTraceRecompositionInjection() {
    run("TraceRecompositionInjection.kt");
  }
}
